[package]
name = "entity"
version = "0.1.0"
edition = "2024"

[lib]
name = "entity"
path = "src/lib.rs"

[dependencies]
sea-orm = "1.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
